name: Remove old artifacts

on:
  schedule:
    # Every day at 1am UTC
    - cron: '0 5 * * *'

jobs:
  remove-old-artifacts:
    if: github.repository == 'automaton-network/automaton-core'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        age: '1 day'
        skip-tags: true
